### ISSUE TITLE
How to set login route 

### ISSUE THREAD

**Issue by bkalidasan79** [htsuruo/flutter-admin-dashboard-template#1]

**Comment by htsuruo** [comment]
@bkalidasan79 

Hi, sorry for late response.

This template doesn't include login route feature as not to depend specific state management package. 

However, this template is used [go_router_builder](https://pub.dev/packages/go_router_builder) so that you can implement login logic with [Redirection](https://pub.dev/documentation/go_router_builder/latest/#redirection) easily. And also, there are some examples of `go_router_builder` and you can find [redirection](https://github.com/flutter/packages/blob/60a1ffc2f77fade3e375a98177729b2f3e90e06e/packages/go_router_builder/example/lib/main.dart#L39-L59) example as expected.  

Depending on the case, you can select the way to manage login session state. I usually use [Riverpod](https://riverpod.dev/) as state management, here is a login route example with `riverpod` and `go_router_builder`.
https://github.com/htsuruo/flutter_amplify_auth_sampler/blob/main/lib/riverpod_based/router.dart 

I hope you implement login route to refer these examples.
